//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MumbaiMallLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mall
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Tel { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> FromDay { get; set; }
        public Nullable<int> ToDay { get; set; }
        public Nullable<System.TimeSpan> Opened { get; set; }
        public Nullable<System.TimeSpan> Closed { get; set; }
    }
}
