//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MumbaiMallLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenHall
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ScreenHall()
        {
            this.ShowTimes = new HashSet<ShowTime>();
        }
    
        public int Id { get; set; }
        public string ScreenName { get; set; }
        public Nullable<int> SeatQty { get; set; }
        public Nullable<int> ServiceProviderId { get; set; }
        public string Avatar { get; set; }
        public Nullable<byte> FromDay { get; set; }
        public Nullable<byte> ToDay { get; set; }
        public Nullable<System.TimeSpan> Opened { get; set; }
        public Nullable<System.TimeSpan> Closed { get; set; }
    
        public virtual ServiceProvider ServiceProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShowTime> ShowTimes { get; set; }
    }
}
