//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MumbaiMallLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int Id { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> CategoryId { get; set; }
    
        public virtual ServiceCategory ServiceCategory { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
    }
}
