//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MumbaiMallLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int Id { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> SeatNo { get; set; }
        public Nullable<int> ShowTimeId { get; set; }
        public Nullable<int> CreditCardId { get; set; }
    
        public virtual CreditCard CreditCard { get; set; }
        public virtual ShowTime ShowTime { get; set; }
    }
}
